// NginxConfigGen.cpp
// Nginx 配置文件生成器实现

#include "../include/NginxConfigGen.h" // 头文件

namespace Cert {

    NginxConfigGenerator::NginxConfigGenerator(     // 构造函数
        const std::string& outputDir,               // 输出目录
        const std::string& domain,                  // 域名
        int httpPort,                               // HTTP 端口
        int httpsPort,                              // HTTPS 端口
        int backendPort,                            // 后端 RPC 端口
        const std::string& staticDir,               // 静态文件目录
        const std::string& certFile,                // 证书文件路径
        const std::string& keyFile)                 // 私钥文件路径
        : m_outputDir(outputDir), m_domain(domain)  // 初始化输出目录和域名
        , m_httpPort(httpPort), m_httpsPort(httpsPort)  // 初始化端口
        , m_backendPort(backendPort)                // 初始化后端端口
        , m_staticDir(staticDir)                    // 初始化静态目录
        , m_certFile(certFile), m_keyFile(keyFile)  // 初始化证书和私钥路径
    {}

    std::string NginxConfigGenerator::generateNginxConf(bool httpsOnly) {  // 生成主配置
        std::ostringstream conf;                    // 配置字符串流

        conf << "# ============================================================\n";
        conf << "# nginx.conf - Auto-generated by CertService\n";
        conf << "# ============================================================\n";
        conf << "# Domain: " << m_domain << "\n";  // 域名
        conf << "# Backend: " << m_backendPort << "\n";  // 后端端口
        conf << "# ============================================================\n\n";

        if (httpsOnly) {                            // 仅 HTTPS 模式
            conf << "server {\n";
            conf << "    listen " << m_httpPort << ";\n";  // HTTP 端口
            conf << "    server_name " << m_domain << ";\n";  // 域名
            conf << "    return 301 https://$host:" << m_httpsPort << "$request_uri;\n";  // 重定向到 HTTPS
            conf << "}\n\n";
        } else {                                    // HTTP + HTTPS 模式
            conf << "server {\n";
            conf << "    listen " << m_httpPort << ";\n";  // HTTP 端口
            conf << "    server_name " << m_domain << ";\n";  // 域名
            conf << "    location / {\n";
            conf << "        root   " << m_staticDir << ";\n";  // 静态文件目录
            conf << "        index  index.html index.htm;\n";
            conf << "        try_files $uri $uri/ /index.html;\n";
            conf << "    }\n";
            conf << "    location /api {\n";
            conf << "        proxy_pass http://10.9.6.28:" << m_backendPort << ";\n";  // 后端代理
            conf << "        proxy_set_header Host $host;\n";
            conf << "        proxy_set_header X-Real-IP $remote_addr;\n";
            conf << "        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n";
            conf << "        proxy_set_header X-Forwarded-Proto $scheme;\n";
            conf << "    }\n";
            conf << "}\n\n";
        }

        conf << "server {\n";
        conf << "    listen " << m_httpsPort << " ssl http2;\n";  // HTTPS 端口
        conf << "    server_name " << m_domain << ";\n\n";  // 域名
        conf << "    ssl_certificate     " << m_certFile << ";\n";  // 证书路径
        conf << "    ssl_certificate_key " << m_keyFile << ";\n";  // 私钥路径
        conf << "    ssl_protocols TLSv1.2 TLSv1.3;\n";
        conf << "    ssl_ciphers HIGH:!aNULL:!MD5;\n";
        conf << "    ssl_prefer_server_ciphers on;\n";
        conf << "    ssl_session_cache shared:SSL:10m;\n";
        conf << "    ssl_session_timeout 10m;\n\n";
        conf << "    add_header Strict-Transport-Security \"max-age=31536000; includeSubDomains\" always;\n";
        conf << "    add_header X-Content-Type-Options nosniff;\n";
        conf << "    add_header X-Frame-Options DENY;\n";
        conf << "    add_header X-XSS-Protection \"1; mode=block\";\n\n";
        conf << "    location / {\n";
        conf << "        root   " << m_staticDir << ";\n";  // 静态文件目录
        conf << "        index  index.html index.htm;\n";
        conf << "        try_files $uri $uri/ /index.html;\n";
        conf << "    }\n\n";
        conf << "    location /api {\n";
        conf << "        proxy_pass http://10.9.6.28:" << m_backendPort << ";\n";  // 后端代理
        conf << "        proxy_set_header Host $host;\n";
        conf << "        proxy_set_header X-Real-IP $remote_addr;\n";
        conf << "        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n";
        conf << "        proxy_set_header X-Forwarded-Proto $scheme;\n";
        conf << "    }\n";
        conf << "}\n";

        return conf.str();                          // 返回配置字符串
    }

    std::string NginxConfigGenerator::generateSslConf() {  // 生成 SSL 片段
        std::ostringstream conf;                    // 配置字符串流
        conf << "# SSL configuration snippet\n";
        conf << "ssl_certificate     " << m_certFile << ";\n";  // 证书路径
        conf << "ssl_certificate_key " << m_keyFile << ";\n";  // 私钥路径
        conf << "ssl_protocols TLSv1.2 TLSv1.3;\n";
        conf << "ssl_ciphers HIGH:!aNULL:!MD5;\n";
        conf << "ssl_prefer_server_ciphers on;\n";
        conf << "ssl_session_cache shared:SSL:10m;\n";
        conf << "ssl_session_timeout 10m;\n";
        return conf.str();                          // 返回配置字符串
    }

    std::string NginxConfigGenerator::generateDockerComposeOverride() {  // 生成 Docker 覆盖
        std::ostringstream conf;                    // 配置字符串流
        conf << "# Docker Compose override for HTTPS\n";
        conf << "services:\n";
        conf << "  nginx:\n";
        conf << "    volumes:\n";
        conf << "      - ./certs:/etc/nginx/certs:ro\n";  // 挂载证书
        conf << "      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro\n";  // 挂载配置
        return conf.str();                          // 返回配置字符串
    }

    std::map<std::string, std::string> NginxConfigGenerator::saveConfigs(bool httpsOnly) {  // 保存所有
        std::filesystem::create_directories(m_outputDir);  // 创建输出目录

        std::map<std::string, std::string> files;   // 文件映射
        files["nginx.conf"] = generateNginxConf(httpsOnly);  // 主配置
        files["ssl.conf"] = generateSslConf();     // SSL 片段
        files["docker-compose.override.yml"] = generateDockerComposeOverride();  // Docker 覆盖

        for (const auto& [name, content] : files) { // 遍历文件
            std::ofstream file(m_outputDir + "/" + name);  // 打开文件
            if (file.good()) {                      // 打开成功
                file << content;                    // 写入内容
            }
        }

        return files;                               // 返回文件映射
    }

} // namespace Cert