#!/usr/bin/env python3
# gen_nginx_conf.py
# 调用 CertService --gen-nginx-only 生成 Nginx 配置

import subprocess       # 子进程
import os               # 文件系统
import sys              # 系统
import json             # JSON
from pathlib import Path  # 路径

def get_cert_service_path():  # 获取 CertService 可执行文件路径
    env_path = os.environ.get("CERT_SERVICE_PATH")
    if env_path:
        return env_path
    
    search_paths = [
        Path(__file__).parent.parent / "build" / "Release" / "CertService.exe",
        Path(__file__).parent.parent / "build" / "CertService",
        Path(__file__).parent.parent / "CertService.exe",
        Path(__file__).parent.parent / "CertService",
    ]
    
    for p in search_paths:
        if p.exists():
            return str(p)
    
    return None

def gen_nginx_conf(  # 生成 Nginx 配置
    nginx_dir="./nginx",
    domain="localhost",
    http_port=80,
    https_port=443,
    backend_port=60906,
    certs_dir="./certs",
    static_dir="/usr/share/nginx/html",
    https_only=False
):
    cert_service = get_cert_service_path()
    if not cert_service:
        print("[ERR] 未找到 CertService 可执行文件")
        print("[ERR] 请先构建 CertService 或设置 CERT_SERVICE_PATH 环境变量")
        return False
    
    cmd = [
        cert_service,
        "--gen-nginx-only",
        "--nginx-dir", nginx_dir,
        "--domain", domain,
        "--http-port", str(http_port),
        "--https-port", str(https_port),
        "--backend-port", str(backend_port),
        "--certs-dir", certs_dir,
        "--static-dir", static_dir,
    ]
    
    if https_only:
        cmd.append("--https-only")
    
    print(f"[CMD] {' '.join(cmd)}")
    result = subprocess.run(cmd, capture_output=True, text=True)
    
    if result.returncode != 0:
        print(f"[ERR] {result.stderr}")
        return False
    
    print(result.stdout)
    
    try:
        data = json.loads(result.stdout)
        if data.get("status") == "success":
            print(f"[OK] Nginx 配置已生成:")
            for f in data.get("files", []):
                print(f"     - {nginx_dir}/{f}")
            return True
    except json.JSONDecodeError:
        pass
    
    return True

def gen_nginx_conf_python(  # 纯 Python 生成（备用，不依赖 C++）
    nginx_dir="./nginx",
    domain="localhost",
    http_port=80,
    https_port=443,
    backend_port=60906,
    certs_dir="./certs",
    static_dir="/usr/share/nginx/html",
    https_only=False
):
    os.makedirs(nginx_dir, exist_ok=True)
    
    cert_file = f"{certs_dir}/server.crt"
    key_file = f"{certs_dir}/server.key"
    
    conf = []
    conf.append("# nginx.conf")
    conf.append("# Auto-generated by gen_nginx_conf.py")
    conf.append(f"# Domain: {domain}")
    conf.append(f"# Backend: {backend_port}")
    conf.append("")
    
    if https_only:
        conf.append("server {")
        conf.append(f"    listen {http_port};")
        conf.append(f"    server_name {domain};")
        conf.append(f"    return 301 https://$host:{https_port}$request_uri;")
        conf.append("}")
        conf.append("")
    else:
        conf.append("server {")
        conf.append(f"    listen {http_port};")
        conf.append(f"    server_name {domain};")
        conf.append("    location / {")
        conf.append(f"        root   {static_dir};")
        conf.append("        index  index.html index.htm;")
        conf.append("        try_files $uri $uri/ /index.html;")
        conf.append("    }")
        conf.append("    location /api {")
        conf.append(f"        proxy_pass http://10.9.6.28:{backend_port};")
        conf.append("        proxy_set_header Host $host;")
        conf.append("        proxy_set_header X-Real-IP $remote_addr;")
        conf.append("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;")
        conf.append("        proxy_set_header X-Forwarded-Proto $scheme;")
        conf.append("    }")
        conf.append("}")
        conf.append("")
    
    conf.append("server {")
    conf.append(f"    listen {https_port} ssl http2;")
    conf.append(f"    server_name {domain};")
    conf.append("")
    conf.append(f"    ssl_certificate     {cert_file};")
    conf.append(f"    ssl_certificate_key {key_file};")
    conf.append("    ssl_protocols TLSv1.2 TLSv1.3;")
    conf.append("    ssl_ciphers HIGH:!aNULL:!MD5;")
    conf.append("    ssl_prefer_server_ciphers on;")
    conf.append("    ssl_session_cache shared:SSL:10m;")
    conf.append("    ssl_session_timeout 10m;")
    conf.append("")
    conf.append('    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;')
    conf.append("    add_header X-Content-Type-Options nosniff;")
    conf.append("    add_header X-Frame-Options DENY;")
    conf.append('    add_header X-XSS-Protection "1; mode=block";')
    conf.append("")
    conf.append("    location / {")
    conf.append(f"        root   {static_dir};")
    conf.append("        index  index.html index.htm;")
    conf.append("        try_files $uri $uri/ /index.html;")
    conf.append("    }")
    conf.append("")
    conf.append("    location /api {")
    conf.append(f"        proxy_pass http://10.9.6.28:{backend_port};")
    conf.append("        proxy_set_header Host $host;")
    conf.append("        proxy_set_header X-Real-IP $remote_addr;")
    conf.append("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;")
    conf.append("        proxy_set_header X-Forwarded-Proto $scheme;")
    conf.append("    }")
    conf.append("}")
    
    nginx_conf_path = os.path.join(nginx_dir, "nginx.conf")
    with open(nginx_conf_path, "w", encoding="utf-8") as f:
        f.write("\n".join(conf))
    
    print(f"[OK] Nginx 配置已生成: {nginx_conf_path}")
    return True

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="生成 Nginx HTTPS 配置")
    parser.add_argument("--nginx-dir", default="./nginx", help="Nginx 配置输出目录")
    parser.add_argument("--domain", default="localhost", help="域名")
    parser.add_argument("--http-port", type=int, default=80, help="HTTP 端口")
    parser.add_argument("--https-port", type=int, default=443, help="HTTPS 端口")
    parser.add_argument("--backend-port", type=int, default=60906, help="后端 RPC 端口")
    parser.add_argument("--certs-dir", default="./certs", help="证书目录")
    parser.add_argument("--static-dir", default="/usr/share/nginx/html", help="静态文件目录")
    parser.add_argument("--https-only", action="store_true", help="仅 HTTPS 模式")
    parser.add_argument("--use-python", action="store_true", help="使用纯 Python 生成（不调用 C++）")
    
    args = parser.parse_args()
    
    if args.use_python:
        success = gen_nginx_conf_python(
            nginx_dir=args.nginx_dir,
            domain=args.domain,
            http_port=args.http_port,
            https_port=args.https_port,
            backend_port=args.backend_port,
            certs_dir=args.certs_dir,
            static_dir=args.static_dir,
            https_only=args.https_only
        )
    else:
        success = gen_nginx_conf(
            nginx_dir=args.nginx_dir,
            domain=args.domain,
            http_port=args.http_port,
            https_port=args.https_port,
            backend_port=args.backend_port,
            certs_dir=args.certs_dir,
            static_dir=args.static_dir,
            https_only=args.https_only
        )
    
    sys.exit(0 if success else 1)